---

- name: Debug
  ansible.builtin.debug:
    msg: "Installing Placement - the OpenStack Placement Service"

- name: Create database
  ansible.builtin.include_tasks: database.yml

- name: Run prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

- name: Install placement
  ansible.builtin.include_tasks: placement.yml

- name: Validate placement
  ansible.builtin.include_tasks: commands.yml

...
