---

- name: Install placement-api packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - placement-api
    - python3-osc-placement

- name: Configure placement connection
  ansible.builtin.lineinfile:
    path: /etc/placement/placement.conf
    regexp: '^connection = sqlite'
    insertafter: '^[database]'
    line: "connection = mysql+pymysql://placement:{{ PLACEMENT_DBPASS }}@controller/placement"

- name: Configure Identity service access
  ansible.builtin.ini_file:
    path: /etc/placement/placement.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "api", option: "auth_strategy", value: "keystone" }
    - { section: "keystone_authtoken", option: "auth_url", value: "http://controller:5000/v3" }
    - { section: "keystone_authtoken", option: "memcached_servers", value: "controller:11211" }
    - { section: "keystone_authtoken", option: "auth_type", value: "password" }
    - { section: "keystone_authtoken", option: "project_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "user_domain_name", value: "Default" }
    - { section: "keystone_authtoken", option: "project_name", value: "service" }
    - { section: "keystone_authtoken", option: "username", value: "placement" }
    - { section: "keystone_authtoken", option: "password", value: "{{ PLACEMENT_PASS }}" }

- name: Initialize the database
  ansible.builtin.shell: su -s /bin/sh -c "placement-manage db sync" placement
  args:
    executable: /bin/bash

- name: Restart apache2
  ansible.builtin.systemd:
    name: apache2.service
    state: restarted

...
