---

- name: Create the nova user
  ansible.builtin.expect:
    command: openstack user create --domain default --password-prompt nova
    responses:
      'User Password': '{{ NOVA_PASS }}'
      'Repeat User Password': '{{ NOVA_PASS }}'
    timeout: 30
  become: true
  become_user: admin-os
  become_flags: -i

- name: Add the admin role to the nova user and service project
  ansible.builtin.shell: |
    openstack role add --project service --user nova admin
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Create the nova service entity
  ansible.builtin.shell: |
    openstack service create --name nova --description "OpenStack Compute" compute
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Create the public nova service API endpoint
  ansible.builtin.shell: openstack endpoint create --region RegionOne compute public http://controller:8774/v2.1 --format json
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i
#  # We need to extract the endpoint ID in the nova installation
#  register: _public_nova_service_api_endpoint

#- name: Debug _public_nova_service_api_endpoint
#  ansible.builtin.debug:
#    msg: "{{ _public_nova_service_api_endpoint }}"

- name: Create the internal nova service API endpoint
  ansible.builtin.shell: |
    openstack endpoint create --region RegionOne compute internal http://controller:8774/v2.1
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Create the admin nova service API endpoint
  ansible.builtin.shell: |
    openstack endpoint create --region RegionOne compute admin http://controller:8774/v2.1
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

...
