---
configs:
  # Select the ansible version
  ansible_version: latest
  # Some tests are integrated into the ansible playbooks
  run_tests: true
  # Vagrant Image
  #vagrant_image: "ubuntu/jammy64"
  vagrant_image: "bento/ubuntu-24.04"
  # vagrant_image: "cloudcourse/noble64"
  vms:
    # Controller Node - Keystone / Glance / Placement / Neutron / Nova / Horizon
    controller:
      # Startup the controller node on vagrant up
      autostart: true
      memory: "6144"
      cpus: "2"
      disk_size: "50GB"
      os_mgt_ip: "10.0.10.10"
      os_pub_ip: "10.0.20.10"
      os_sdn_ip: "10.0.30.10"
      ceph_public_ip: "10.0.40.10"
      ceph_cluster_ip: "10.0.50.10"
      domain: controller
      aliases:
      - controller.os.lokal
    # Compute Node - Neutron / Nova / Cinder
    compute1:
      autostart: true
      memory: "8192"
      cpus: "4"
      disk_size: "50GB"
      storage_disk_size: "100GB"
      os_mgt_ip: "10.0.10.11"
      os_pub_ip: "10.0.20.11"
      os_sdn_ip: "10.0.30.11"
      ceph_public_ip: "10.0.40.11"
      ceph_cluster_ip: "10.0.50.11"
      domain: compute1
      aliases:
      - compute1.os.lokal
    compute2:
      autostart: true
      memory: "8192"
      cpus: "4"
      disk_size: "50GB"
      storage_disk_size: "100GB"
      os_mgt_ip: "10.0.10.12"
      os_pub_ip: "10.0.20.12"
      os_sdn_ip: "10.0.30.12"
      ceph_public_ip: "10.0.40.12"
      ceph_cluster_ip: "10.0.50.12"
      domain: compute2
      aliases:
      - compute2.os.lokal
...
