---
configs:
  # Select the ansible version
  ansible_version: latest
  # Some tests are integrated into the ansible playbooks
  run_tests: true
  # Vagrant Image
  #vagrant_image: "ubuntu/jammy64"
  vagrant_image: "bento/ubuntu-24.04"
  # vagrant_image: "cloudcourse/noble64"
  vms:
    # Controller Node - Keystone / Glance / Placement / Neutron / Nova / Horizon
    controller:
      # Startup the controller node on vagrant up
      autostart: true
      memory: "6144"
      cpus: "2"
      disk_size: "50GB"
      internal_ip: "10.0.0.10"
      ceph_ip: "10.0.1.10"
      domain: controller
      aliases:
      - controller.os.lokal
    # Compute Node - Neutron / Nova / Cinder
    compute1:
      autostart: false
      memory: "8192"
      cpus: "4"
      disk_size: "50GB"
      storage_disk_size: "100GB"
      internal_ip: "10.0.0.11"
      ceph_ip: "10.0.1.11"
      domain: compute1
      aliases:
      - compute1.os.lokal
    compute2:
      autostart: false
      memory: "8192"
      cpus: "4"
      disk_size: "50GB"
      storage_disk_size: "100GB"
      internal_ip: "10.0.0.12"
      ceph_ip: "10.0.1.12"
      domain: compute1
      aliases:
      - compute1.os.lokal
...
