---

- name: Prerequisites Chrony
  hosts: all
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:

    - name: Load ansible vars, if existent
      ansible.builtin.include_vars:
        file: ansible_vars.yml

    - name: Set the hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        dpkg_options: 'force-confnew,force-confdef'
        autoclean: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      register: apt_upgrade_result
      until: apt_upgrade_result is succeeded
      retries: 5
      delay: 10 # seconds

    - name: Install dependencies packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        dpkg_options: 'force-confnew,force-confdef'
        autoclean: true
        autoremove: true
        update_cache: true
        cache_valid_time: 3600
      vars:
        packages:
          - curl
          - jq
          - acl
      register: apt_result
      until: apt_result is succeeded
      retries: 5
      delay: 10 # seconds

  roles:
    - chrony

- name: Controller Dependencies
  hosts: openstack_controller
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:

    - name: Load ansible vars, if existent
      ansible.builtin.include_vars:
        file: ansible_vars.yml

  roles:
    - openstack_controller_dependencies

- name: Prerequisites Ceph
  hosts: ceph_nodes
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:

    - name: Load ansible vars, if existent
      ansible.builtin.include_vars:
        file: ansible_vars.yml

  roles:
    - ceph_common

- name: Install ceph monitors
  hosts: ceph_mons
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:

    - name: Load ansible vars, if existent
      ansible.builtin.include_vars:
        file: ansible_vars.yml

  roles:
    - ceph_mon

...
