---
- hosts: all
  gather_facts: true
  become: true
  become_method: sudo

  vars:
    some_var: true

  pre_tasks:

  - name: Install dependencies packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: true
      autoremove: true
      update_cache: true
      cache_valid_time: 3600
    vars:
      packages:
      - curl

  - name: Install cloud-archive:bobcat
    command: add-apt-repository cloud-archive:bobcat -y

  roles:
  - 01_keystone

  tasks:

  - name: Debug
    ansible.builtin.debug:
      msg: "Task"
