---
- hosts: openstack-compute
  gather_facts: true
  become: true
  become_method: sudo

  pre_tasks:

  - name: Load ansible vars, if existent
    ansible.builtin.include_vars:
      file: ansible_vars.yml

  - name: Set the hostname
    ansible.builtin.hostname:
      name: "{{ ansible_hostname }}"

  - name: Update hosts file
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^127.0.0.1'
      line: "127.0.0.1 localhost {{ ansible_hostname }}"

  - name: Install dependencies packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      dpkg_options: 'force-confnew,force-confdef'
      autoclean: true
      autoremove: true
      update_cache: true
      cache_valid_time: 3600
    vars:
      packages:
      - curl
      - jq

  #- name: Install cloud-archive:epoxy
  #  command: add-apt-repository cloud-archive:epoxy -y
  #- name: Install cloud-archive:caracal
  #  command: add-apt-repository cloud-archive:caracal -y
  # - name: Install cloud-archive:bobcat
  #   command: add-apt-repository cloud-archive:bobcat -y
  # - name: Install cloud-archive:antelope
  #   command: add-apt-repository cloud-archive:antelope -y

  roles:
  - 01_compute_00_dependencies
  - 01_compute_01_neutron
  - 01_compute_02_nova
  - 01_compute_03_cinder

  tasks:

  - name: Debug
    ansible.builtin.debug:
      msg: "Task"
