---

- name: Install keystone packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - keystone

- name: Configure keystone connection
  ansible.builtin.ini_file:
    path: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: "database", option: "connection", value: "mysql+pymysql://keystone:{{ KEYSTONE_DBPASS }}@controller/keystone" }

- name: Configure rabbitmq access
  ansible.builtin.ini_file:
    path: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{ RABBIT_PASS }}@controller:5672/" }

- name: Configure keystone token provider
  ansible.builtin.ini_file:
    path: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: "receipt", option: "provider", value: "fernet" }

- name: Configure keystone memcached
  ansible.builtin.ini_file:
    path: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: "cache", option: "memcache_servers", value: "controller:11211" }

- name: Initialize the database
  ansible.builtin.shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
  args:
    executable: /bin/bash
    # creates: /var/log/keystone/keystone-manage.log
    creates: /var/lib/mysql/keystone/alembic_version.ibd

- name: Initialize Fernet key repositories
  ansible.builtin.shell: |
    keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone && \
    keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  args:
    executable: /bin/bash
    creates: /etc/keystone/fernet-keys/0

- name: Bootstrap the Identity service
  ansible.builtin.shell: |
    keystone-manage bootstrap --bootstrap-password {{ ADMIN_PASS }} \
    --bootstrap-admin-url http://controller:5000/v3/ \
    --bootstrap-internal-url http://controller:5000/v3/ \
    --bootstrap-public-url http://controller:5000/v3/ \
    --bootstrap-region-id RegionOne
  args:
    executable: /bin/bash
    creates: /opt/os-deployment-progress/keystone-bootstrap

- name: Touch /opt/os-deployment-progress/keystone-bootstrap for idempotency
  ansible.builtin.file:
    path: /opt/os-deployment-progress/keystone-bootstrap
    state: touch
    owner: root
    group: root
    mode: '0755'

- name: Configure apache2.conf
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerName'
    insertafter: '^#ServerRoot'
    line: ServerName controller

...
