---

- name: Debug
  ansible.builtin.debug:
    msg: "Installing Keystone - the OpenStack Identiy Service"

- name: Create database
  ansible.builtin.include_tasks: database.yml

- name: Install keystone
  ansible.builtin.include_tasks: keystone.yml

- name: Create necessary resources
  ansible.builtin.include_tasks: commands.yml

- name: Create a domain, projects, users, and roles
  ansible.builtin.include_tasks: tests.yml
  when: RUN_TESTS

...
