---

dependencies:
  - role: ceph_common

galaxy_info:
  author: OpenStack in a Nutshell
  description: Ceph OSD configuration role
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - ceph
    - storage
    - osd
    - openstack
