---

- name: Debug
  ansible.builtin.debug:
    msg: "Installing Glance - the OpenStack Image Service"

- name: Install dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Run prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

#- name: Install glance
#  ansible.builtin.include_tasks: glance.yml

...
