---

- name: Create glance user
  ansible.builtin.expect:
    command: openstack user create --domain default --password-prompt glance
    responses:
      'User Password': 'qwertz'
      'Repeat User Password': 'qwertz'
    timeout: 30
  become: true
  become_user: admin-os
  become_flags: -i

- name: Add the admin role to the glance user and service project
  ansible.builtin.shell: |
    openstack role add --project service --user glance admin
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Create the glance service entity
  ansible.builtin.shell: |
    openstack service create --name glance --description "OpenStack Image" image
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Create the Image service API endpoints
  ansible.builtin.shell: |
    openstack endpoint create --region RegionOne image public http://controller:9292 && \
    openstack endpoint create --region RegionOne image internal http://controller:9292 && \
    openstack endpoint create --region RegionOne image admin http://controller:9292
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Register quota limits
  ansible.builtin.shell: |
    openstack --os-cloud devstack-system-admin registered limit create --service glance --default-limit 1000 --region RegionOne image_size_total && \
    openstack --os-cloud devstack-system-admin registered limit create --service glance --default-limit 1000 --region RegionOne image_stage_total && \
    openstack --os-cloud devstack-system-admin registered limit create --service glance --default-limit 100 --region RegionOne image_count_total && \
    openstack --os-cloud devstack-system-admin registered limit create --service glance --default-limit 100 --region RegionOne image_count_uploading
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

...
