---

# Handlers for ceph_mon role
- name: Restart ceph-mon
  ansible.builtin.systemd:
    name: "ceph-mon@{{ inventory_hostname }}.service"
    state: restarted
  listen: Restart ceph-mon # Custom listener name

# Assuming you will have a separate mgr role or include mgr tasks here later
# - name: Restart ceph-mgr
#   ansible.builtin.systemd:
#     name: "ceph-mgr@{{ inventory_hostname }}.service"
#     state: restarted
#   listen: Restart ceph-mgr

...
