---

- name: Install dependencies packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - python3-openstackclient
    - mariadb-server
    - python3-pymysql
    - rabbitmq-server
    - memcached
    - python3-memcache

- name: Create mariadb.conf.d/99-openstack.cnf
  ansible.builtin.copy:
    src: 99-openstack.cnf
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf

- name: Restart mariadb
  ansible.builtin.systemd:
    name: mariadb.service
    state: restarted

- name: Secure mariadb
  ansible.builtin.expect:
    command: mysql_secure_installation
    responses:
      'Enter current password for root': ''
      'Switch to unix_socket authentication': 'n'
      'Change the root password': 'y'
      'New password': 'qwertz'
      'Re-enter new password': 'qwertz'
      'Remove anonymous users': 'y'
      'Disallow root login remotely': 'y'
      'Remove test database': 'y'
      'Reload privilege tables now': 'y'
    timeout: 1
    creates: /root/.my.cnf
  register: secure_mariadb
  failed_when: "'... Failed!' in secure_mariadb.stdout_lines"

- name: Create root/.my.cnf
  ansible.builtin.copy:
    src: my.cnf
    dest: /root/.my.cnf

- name: Create the keystone database
  community.mysql.mysql_db:
    name: keystone
    state: present

- name: Create user keytone and give all permissions to keystone from localhost
  community.mysql.mysql_user:
    name: keystone
    password: qwertz
    priv: 'keystone.*:ALL'
    host: localhost
    state: present

- name: Create user keytone and give all permissions to keystone from %
  community.mysql.mysql_user:
    name: keystone
    password: qwertz
    priv: 'keystone.*:ALL'
    host: '%'
    state: present

- name: Make rabbitmq listen on public interface
  ansible.builtin.lineinfile:
    path: /etc/rabbitmq/rabbitmq-env.conf
    regexp: '^NODE_IP_ADDRESS'
    insertafter: '^#NODE_IP_ADDRESS'
    line: NODE_IP_ADDRESS=0.0.0.0

- name: Restart rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server.service
    state: restarted

- name: Set rabbitmq user
  ansible.builtin.shell: |
    rabbitmqctl add_user openstack qwertz && \
    rabbitmqctl set_permissions openstack ".*" ".*" ".*"
  args:
    executable: /bin/bash

- name: Make memcahed listen on public interface
  ansible.builtin.lineinfile:
    path: /etc/memcached.conf
    regexp: '^-l '
    line: -l 0.0.0.0

- name: Restart memcached
  ansible.builtin.systemd:
    name: memcached.service
    state: restarted

...
