---

- name: Debug
  ansible.builtin.debug:
    msg: "Installing Ceph - the OpenStack Storage Backend"

#- name: Create database
#  ansible.builtin.include_tasks: database.yml

#- name: Run prerequisites
#  ansible.builtin.include_tasks: prerequisites.yml

- name: Install ceph
  ansible.builtin.include_tasks: ceph.yml

- name: Validate ceph
  ansible.builtin.include_tasks: tests.yml
  when: RUN_TESTS

...
