---

- name: Create the cinder user
  ansible.builtin.expect:
    command: openstack user create --domain default --password-prompt cinder
    responses:
      'User Password': '{{ CINDER_PASS }}'
      'Repeat User Password': '{{ CINDER_PASS }}'
    timeout: 30
    creates: /opt/os-deployment-progress/cinder-user
  become: true
  become_user: admin-os
  become_flags: -i

- name: Touch /opt/os-deployment-progress/cinder-user for idempotency
  ansible.builtin.file:
    path: /opt/os-deployment-progress/cinder-user
    state: touch
    owner: root
    group: root
    mode: '0755'

- name: Add the admin role to the cinder user and service project
  ansible.builtin.shell: |
    openstack role add --project service --user cinder admin
  args:
    executable: /bin/bash
    creates: /opt/os-deployment-progress/cinder-admin
  become: true
  become_user: admin-os
  become_flags: -i

- name: Touch /opt/os-deployment-progress/cinder-admin for idempotency
  ansible.builtin.file:
    path: /opt/os-deployment-progress/cinder-admin
    state: touch
    owner: root
    group: root
    mode: '0755'

- name: Create the cinderv3 service entity
  ansible.builtin.shell: |
    openstack service create --name cinderv3 --description "OpenStack Block Storage" volumev3
  args:
    executable: /bin/bash
    creates: /opt/os-deployment-progress/cinder-volume
  become: true
  become_user: admin-os
  become_flags: -i

- name: Touch /opt/os-deployment-progress/cinder-volume for idempotency
  ansible.builtin.file:
    path: /opt/os-deployment-progress/cinder-volume
    state: touch
    owner: root
    group: root
    mode: '0755'

- name: Create the public cinder service API endpoint
  ansible.builtin.shell: |
    openstack endpoint create --region RegionOne volumev3 public http://controller:8776/v3/%\(project_id\)s
  args:
    executable: /bin/bash
    creates: /opt/os-deployment-progress/cinder-endpoint-public
  become: true
  become_user: admin-os
  become_flags: -i

- name: Touch /opt/os-deployment-progress/cinder-endpoint-public for idempotency
  ansible.builtin.file:
    path: /opt/os-deployment-progress/cinder-endpoint-public
    state: touch
    owner: root
    group: root
    mode: '0755'

- name: Create the internal cinder service API endpoint
  ansible.builtin.shell: |
    openstack endpoint create --region RegionOne volumev3 internal http://controller:8776/v3/%\(project_id\)s
  args:
    executable: /bin/bash
    creates: /opt/os-deployment-progress/cinder-endpoint-internal
  become: true
  become_user: admin-os
  become_flags: -i

- name: Touch /opt/os-deployment-progress/cinder-endpoint-internal for idempotency
  ansible.builtin.file:
    path: /opt/os-deployment-progress/cinder-endpoint-internal
    state: touch
    owner: root
    group: root
    mode: '0755'

- name: Create the admin cinder service API endpoint
  ansible.builtin.shell: |
    openstack endpoint create --region RegionOne volumev3 admin http://controller:8776/v3/%\(project_id\)s
  args:
    executable: /bin/bash
    creates: /opt/os-deployment-progress/cinder-endpoint-admin
  become: true
  become_user: admin-os
  become_flags: -i

- name: Touch /opt/os-deployment-progress/cinder-endpoint-admin for idempotency
  ansible.builtin.file:
    path: /opt/os-deployment-progress/cinder-endpoint-admin
    state: touch
    owner: root
    group: root
    mode: '0755'

...
