---

- name: Download the cirros image
  ansible.builtin.get_url:
    url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
    dest: ./cirros-0.4.0-x86_64-disk.img

- name: Upload the image to the Image service
  ansible.builtin.shell: |
    glance image-create --name "cirros" \
    --file cirros-0.4.0-x86_64-disk.img \
    --disk-format qcow2 --container-format bare \
    --visibility=public
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: List the image
  ansible.builtin.shell: |
    glance image-list
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

...
