---

- name: Create glance user
  ansible.builtin.expect:
    command: openstack user create --domain default --password-prompt glance
    responses:
      'User Password': '{{ GLANCE_PASS }}'
      'Repeat User Password': '{{ GLANCE_PASS }}'
    timeout: 30
  become: true
  become_user: admin-os
  become_flags: -i

- name: Add the admin role to the glance user and service project
  ansible.builtin.shell: |
    openstack role add --project service --user glance admin
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Make sure that the glance account has reader access to system-scope resources
  ansible.builtin.shell: |
    openstack role add --user glance --user-domain Default --system all reader
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Create the glance service entity
  ansible.builtin.shell: |
    openstack service create --name glance --description "OpenStack Image" image
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Create the public Image service API endpoint
  ansible.builtin.shell: openstack endpoint create --region RegionOne image public http://controller:9292 --format json
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i
  # We need to extract the endpoint ID in the glance installation
  register: _public_image_service_api_endpoint

- name: Debug _public_image_service_api_endpoint
  ansible.builtin.debug:
    msg: "{{ _public_image_service_api_endpoint }}"

- name: Create the internal Image service API endpoint
  ansible.builtin.shell: |
    openstack endpoint create --region RegionOne image internal http://controller:9292
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Create the admin Image service API endpoint
  ansible.builtin.shell: |
    openstack endpoint create --region RegionOne image admin http://controller:9292
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

- name: Register quota limits
  ansible.builtin.shell: |
    openstack registered limit create --service glance --default-limit 1000 --region RegionOne image_size_total && \
    openstack registered limit create --service glance --default-limit 1000 --region RegionOne image_stage_total && \
    openstack registered limit create --service glance --default-limit 100 --region RegionOne image_count_total && \
    openstack registered limit create --service glance --default-limit 100 --region RegionOne image_count_uploading
  args:
    executable: /bin/bash
  become: true
  become_user: admin-os
  become_flags: -i

...
