---

- name: Restart ceph.mon
  ansible.builtin.systemd:
    name: memcached.service
    state: restarted
  changed_when: false

- name: Create temp monmap
  ansible.builtin.command:
    cmd: "ceph --cluster ceph mon getmap -o /tmp/monmap"
    creates: "/tmp/monmap"

- name: Create temp ceph.mon.keyring
  ansible.builtin.command:
    cmd: "ceph --cluster ceph auth get mon. -o /tmp/ceph.mon.keyring"
    creates: "/tmp/ceph.mon.keyring"

- name: Fetch the ceph.client.admin.keyring from monitor node
  ansible.builtin.fetch:
    src: /etc/ceph/ceph.client.admin.keyring
    dest: share/ceph.client.admin.keyring
    flat: yes

- name: Fetch the monmap from monitor node
  ansible.builtin.fetch:
    src: /tmp/monmap
    dest: share/monmap
    flat: yes

- name: Fetch the ceph.mon.keyring from monitor node
  ansible.builtin.fetch:
    src: /tmp/ceph.mon.keyring
    dest: share/ceph.mon.keyring
    flat: yes

- name: Remove temp monmap
  ansible.builtin.file:
    path: /tmp/monmap
    state: absent

- name: Remove temp ceph.mon.keyring
  ansible.builtin.file:
    path: /tmp/ceph.mon.keyring
    state: absent

...
