---

- name: Install Ceph monitor packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - ceph-mon

- name: Run on first monitor
  when: inventory_hostname == ansible_play_hosts_all[0]
  block:

  - name: Initialize first monitor
    ansible.builtin.include_tasks: ceph_mon_initial_setup.yml

- name: Update configuration
  ansible.builtin.include_tasks: ceph_mon_config.yml

- name: Run on first monitor
  when: inventory_hostname == ansible_play_hosts_all[0]
  block:

  - name: Extract Files from initial monitor
    ansible.builtin.include_tasks: ceph_mon_extract_secrets.yml

- name: Run on additional monitors
  when: inventory_hostname != ansible_play_hosts_all[0]
  block:

  - name: Add addtitonal monitor
    ansible.builtin.include_tasks: ceph_mon_add.yml

...
