---

- name: Create the cinder database
  community.mysql.mysql_db:
    name: cinder
    state: present

- name: Create user cinder and give all permissions to cinder from localhost
  community.mysql.mysql_user:
    name: cinder
    password: "{{ CINDER_DBPASS }}"
    priv: 'cinder.*:ALL'
    host: localhost
    state: present
    append_privs: true

- name: Create user cinder and give all permissions to cinder from %
  community.mysql.mysql_user:
    name: cinder
    password: "{{ CINDER_DBPASS }}"
    priv: 'cinder.*:ALL'
    host: '%'
    state: present
    append_privs: true

...
